"""Init

Revision ID: 3b509ff02713
Revises: 
Create Date: 2026-03-15 14:32:20.790330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3b509ff02713'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_local', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sala', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('predio', sa.Integer(), nullable=True),
    sa.Column('andar', sa.Integer(), nullable=True),
    sa.Column('tipo_ambiente', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('observacao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('setor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quantidade_projetores', sa.Integer(), nullable=False),
    sa.Column('saida_projetor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tomada_padrao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('adaptador_dp_vga', sa.Integer(), nullable=False),
    sa.Column('adaptador_dp_hdmi', sa.Integer(), nullable=False),
    sa.Column('adaptador_hdmi_vga', sa.Integer(), nullable=False),
    sa.Column('adaptador_duplicador_vga', sa.Integer(), nullable=False),
    sa.Column('adaptador_outros', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ultimo_responsavel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ultimo_contato', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locais_local_id'), 'locais', ['local_id'], unique=True)
    op.create_table('historicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_ref_id', sa.Integer(), nullable=True),
    sa.Column('local_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('observacao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('responsavel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contato', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mensagem_original', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['local_ref_id'], ['locais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historicos_created_at'), 'historicos', ['created_at'], unique=False)
    op.create_index(op.f('ix_historicos_local_id'), 'historicos', ['local_id'], unique=False)
    op.create_table('maquinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_ref_id', sa.Integer(), nullable=False),
    sa.Column('modelo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('processador', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('propriedade', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ram_gb', sa.Integer(), nullable=True),
    sa.Column('ram_modelo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ram_tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('armazenamento_gb', sa.Integer(), nullable=True),
    sa.Column('armazenamento_modelo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('armazenamento_tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('video_dp', sa.Integer(), nullable=False),
    sa.Column('video_hdmi', sa.Integer(), nullable=False),
    sa.Column('video_vga', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['local_ref_id'], ['locais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maquinas_local_ref_id'), 'maquinas', ['local_ref_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maquinas_local_ref_id'), table_name='maquinas')
    op.drop_table('maquinas')
    op.drop_index(op.f('ix_historicos_local_id'), table_name='historicos')
    op.drop_index(op.f('ix_historicos_created_at'), table_name='historicos')
    op.drop_table('historicos')
    op.drop_index(op.f('ix_locais_local_id'), table_name='locais')
    op.drop_table('locais')
    # ### end Alembic commands ###
